/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : NSSpeechRecognizer
 #	author : miyako
 #	2018/05/10
 #
 # --------------------------------------------------------------------------------*/

#include "libjson.h"

// --- NSSpeechRecognizer
void START_SPEECH_RECOGNIZER(sLONG_PTR *pResult, PackagePtr pParams);
void SET_SPEECH_COMMANDS(sLONG_PTR *pResult, PackagePtr pParams);
void GET_SPEECH_COMMANDS(sLONG_PTR *pResult, PackagePtr pParams);
void STOP_SPEECH_RECOGNIZER(sLONG_PTR *pResult, PackagePtr pParams);
void QUIT_SPEECH_RECOGNIZER(sLONG_PTR *pResult, PackagePtr pParams);

void listenerInit(void);
void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;
